### ISSUE TITLE
Azure Information Protection - Protection activation An unexpected error occured

### ISSUE THREAD

**Issue by stedey** [MicrosoftDocs/Azure-RMSDocs.zh-cn#19]
An unexpected error occured, please try again later.

Error - Rms Provisioning In Progress
We’re still setting up Azure Information Protection for your organization. This provisioning process can take up to two hours after a subscription for this service is added to your tenant.

**Comment by CeciAc** [comment]
Hi @stedey 
Could you give us more detailed information on which is the issue?
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Closed due lack of action items.
